from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from rich.console import Console

from src.agents.hydrologist import Hydrologist
from src.agents.surveyor import Surveyor
from src.graph.knowledge_graph import KnowledgeGraph

logger = logging.getLogger(__name__)
console = Console()
_surveyor = Surveyor()
_hydro = Hydrologist()

FIVE_QUESTIONS = [
    "What is the primary data ingestion path?",
    "What are the 3–5 most critical output datasets or endpoints?",
    "What is the blast radius if the most critical module fails?",
    "Where is the business logic concentrated vs. distributed?",
    "What has changed most frequently in the last 90 days?",
]


class Archivist:
    """Agent 4: Living Context Maintainer.

    Produces CODEBASE.md, onboarding_brief.md, cartography_trace.jsonl,
    and the ChromaDB semantic index.
    """

    def produce_artifacts(
        self,
        kg: KnowledgeGraph,
        output_dir: Path,
        day_one_answers: Optional[dict] = None,
        repo_commit: str = "",
    ) -> None:
        console.print("[bold cyan]Archivist[/bold cyan] — generating output artifacts…")
        output_dir.mkdir(parents=True, exist_ok=True)

        kg.save(output_dir)

        codebase_md = self.generate_CODEBASE_md(kg, day_one_answers or {})
        (output_dir / "CODEBASE.md").write_text(codebase_md, encoding="utf-8")

        brief_md = self.generate_onboarding_brief(day_one_answers or {}, kg)
        (output_dir / "onboarding_brief.md").write_text(brief_md, encoding="utf-8")

        self.log_trace(
            action="full_analysis_complete",
            agent="archivist",
            evidence_source="all_agents",
            confidence=1.0,
            output_dir=output_dir,
            extra={"repo_commit": repo_commit, "stats": kg.stats()},
        )

        console.print(f"  [green]✓[/green] Artifacts written to [bold]{output_dir}[/bold]")
        console.print(f"     • CODEBASE.md")
        console.print(f"     • onboarding_brief.md")
        console.print(f"     • module_graph.json")
        console.print(f"     • lineage_graph.json")
        console.print(f"     • cartography_trace.jsonl")

    def generate_CODEBASE_md(self, kg: KnowledgeGraph, day_one_answers: dict) -> str:
        top_modules = _surveyor.top_modules_by_pagerank(kg, n=5)
        sources = _hydro.find_sources(kg)
        sinks = _hydro.find_sinks(kg)
        high_vel = sorted(kg.all_modules(), key=lambda m: m.change_velocity_30d, reverse=True)[:10]
        cycles = [m.path for m in kg.all_modules() if m.in_cycle]
        drift = [m for m in kg.all_modules() if m.documentation_drift]

        # Domain clusters
        domains: dict[str, list] = {}
        for m in kg.all_modules():
            cluster = m.domain_cluster or "uncategorized"
            domains.setdefault(cluster, []).append(m)

        sections: list[str] = []
        sections.append("# CODEBASE.md — Living Architectural Context\n")
        sections.append(f"> Auto-generated by Brownfield Cartographer on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}\n")

        # Architecture overview
        if top_modules:
            top_names = ", ".join(f"`{m.path}`" for m in top_modules[:3])
            domain_names = ", ".join(sorted(domains.keys())[:5])
            overview = (
                f"This codebase contains {len(kg.all_modules())} modules organized across "
                f"{len(domains)} inferred domains: {domain_names}. "
                f"The architectural hubs (highest PageRank) are {top_names}. "
                f"There are {len(sources)} data sources, {len(sinks)} data sinks, "
                f"and {len(cycles)} circular dependency groups."
            )
        else:
            overview = "No modules analyzed yet."

        sections.append("## Architecture Overview\n")
        sections.append(overview + "\n")

        # Critical path
        sections.append("\n## Critical Path (Top Modules by Importance)\n")
        sections.append("| Module | Domain | PageRank | Purpose |\n")
        sections.append("|--------|--------|----------|--------|\n")
        for m in top_modules:
            purpose = (m.purpose_statement or "—")[:80].replace("|", "\\|")
            sections.append(f"| `{m.path}` | {m.domain_cluster or '—'} | {m.pagerank_score:.4f} | {purpose} |\n")

        # Data sources and sinks
        sections.append("\n## Data Sources & Sinks\n")
        if sources:
            sections.append("### Sources (entry points)\n")
            for s in sources[:15]:
                sections.append(f"- **{s.name}** ({s.storage_type}) — `{s.source_file or '?'}`\n")
        if sinks:
            sections.append("\n### Sinks (final outputs)\n")
            for s in sinks[:15]:
                sections.append(f"- **{s.name}** ({s.storage_type})\n")

        # Known debt
        sections.append("\n## Known Debt\n")
        if cycles:
            sections.append(f"### Circular Dependencies ({len(cycles)} modules)\n")
            for path in cycles[:10]:
                sections.append(f"- `{path}`\n")
        if drift:
            sections.append(f"\n### Documentation Drift ({len(drift)} files)\n")
            for m in drift[:10]:
                sections.append(f"- `{m.path}` — docstring contradicts implementation\n")
        if not cycles and not drift:
            sections.append("No circular dependencies or documentation drift detected.\n")

        # High-velocity files
        sections.append("\n## High-Velocity Files (most frequently changed)\n")
        sections.append("| File | Commits (30d) |\n")
        sections.append("|------|---------------|\n")
        for m in high_vel:
            if m.change_velocity_30d > 0:
                sections.append(f"| `{m.path}` | {m.change_velocity_30d} |\n")

        # Domain map
        if domains:
            sections.append("\n## Domain Architecture Map\n")
            for domain, mods in sorted(domains.items()):
                sections.append(f"\n### {domain.title()} ({len(mods)} modules)\n")
                for m in sorted(mods, key=lambda x: x.pagerank_score, reverse=True)[:5]:
                    sections.append(f"- `{m.path}`\n")

        # Module purpose index
        sections.append("\n## Module Purpose Index\n")
        sections.append("| Module | Domain | Purpose |\n")
        sections.append("|--------|--------|---------|\n")
        for m in sorted(kg.all_modules(), key=lambda x: x.pagerank_score, reverse=True):
            if m.purpose_statement:
                purpose = m.purpose_statement[:100].replace("|", "\\|").replace("\n", " ")
                sections.append(f"| `{m.path}` | {m.domain_cluster or '—'} | {purpose} |\n")

        return "".join(sections)

    def generate_onboarding_brief(self, day_one_answers: dict, kg: KnowledgeGraph) -> str:
        lines: list[str] = []
        lines.append("# FDE Onboarding Brief\n")
        lines.append(f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}\n\n")
        lines.append("## The Five Day-One Questions\n\n")

        for i, question in enumerate(FIVE_QUESTIONS, 1):
            answer = day_one_answers.get(question, "_Not yet answered_")
            lines.append(f"### {i}. {question}\n\n")
            lines.append(f"{answer}\n\n")

        # Quick reference
        top_modules = _surveyor.top_modules_by_pagerank(kg, n=5)
        sources = _hydro.find_sources(kg)
        sinks = _hydro.find_sinks(kg)

        lines.append("---\n\n## Quick Reference\n\n")
        lines.append("### Critical Modules\n")
        for m in top_modules:
            lines.append(f"- `{m.path}` (PageRank: {m.pagerank_score:.4f})\n")

        lines.append("\n### Entry Points (data sources)\n")
        for s in sources[:10]:
            lines.append(f"- `{s.name}` — `{s.source_file or '?'}`\n")

        lines.append("\n### Final Outputs (data sinks)\n")
        for s in sinks[:10]:
            lines.append(f"- `{s.name}`\n")

        return "".join(lines)

    def build_semantic_index(self, kg: KnowledgeGraph, output_dir: Path) -> None:
        """Embed all module purpose statements into ChromaDB."""
        modules_with_statements = [m for m in kg.all_modules() if m.purpose_statement]
        if not modules_with_statements:
            return

        try:
            import chromadb
            from chromadb.config import Settings

            index_dir = output_dir / "semantic_index"
            index_dir.mkdir(exist_ok=True)

            client = chromadb.PersistentClient(path=str(index_dir))
            collection = client.get_or_create_collection("modules")

            existing = set(collection.get()["ids"])
            new_modules = [m for m in modules_with_statements if m.path not in existing]

            if new_modules:
                collection.add(
                    documents=[m.purpose_statement for m in new_modules],
                    metadatas=[{"path": m.path, "domain": m.domain_cluster} for m in new_modules],
                    ids=[m.path for m in new_modules],
                )
                console.print(f"  [green]✓[/green] Semantic index: {len(new_modules)} modules indexed")
        except Exception as exc:
            logger.warning("Semantic index build failed: %s", exc)

    def log_trace(
        self,
        action: str,
        agent: str,
        evidence_source: str,
        confidence: float,
        output_dir: Optional[Path] = None,
        extra: Optional[dict] = None,
    ) -> None:
        if output_dir is None:
            return
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent": agent,
            "action": action,
            "evidence_source": evidence_source,
            "confidence_level": confidence,
            **(extra or {}),
        }
        trace_path = output_dir / "cartography_trace.jsonl"
        with open(trace_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
